export const ColorTypes = [
  {
    name: "Wood",
    color: "#A1662F",
    colorvalue: 0xa1662f,
  },
  {
    name: "Chromium",
    color: "#c6c8c9",
    colorvalue: 0xc6c8c9,
  },
  {
    name: "Gold",
    color: "#FFD700",
    colorvalue: 0xffd700,
  },
  {
    name: "Silver",
    color: "#C0C0C0",
    colorvalue: 0xc0c0c0,
  },
  {
    name: "Nickel",
    color: "#727472",
    colorvalue: 0x727472,
  },
];
export const AllProducts = [
  {
    id: "6515",
    name: "Metal Door with half vision kit 3' X 7'",
    category: "Door with Frame",
    Company: "Fleming",
    price: "1000",
    model: "door2.glb",
    title: "Metal Door with half vision kit 3' X 7'",
    description:
      "Commerical steel grade doors and frame suitable for 3' x 7' with stylish half vision window. \n The finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/door2.png", "/assets/door1.png", "/assets/door3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "1455",
    name: "Metal Door with full vision kit 3' X 7'",
    category: "Door with Frame",
    Company: "CECO",
    price: "800",
    model: "door3.glb",
    title: "Metal Door with full vision kit 3' X 7'",
    description:
      "Commerical steel grade doors and frame suitable for 3' x 7' with stylish half vision window.\nThe finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/s1.png", "/assets/s2.png", "/assets/s3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "6504",
    name: "Single Door with FRV vision 4' x 8'",
    category: "Door with Frame",
    Company: "Curries",
    price: "1000",
    model: "door4.glb",
    title: "Single Door with FRV vision 4' x 8'",
    description:
      "Commerical steel grade doors and frame suitable for 4' x 8' with stylish FRV window. \nThe finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/f1.png", "/assets/f2.png", "/assets/f3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "7845",
    name: "Metal door - W/Without Vision",
    category: "Door",
    Company: "Curries",
    price: "1550",
    model: "door5.glb",
    title: "Metal door - W/Without Vision",
    description: "Commerical steel grade doors as per your required size",
    images: ["/assets/door2.png", "/assets/door1.png", "/assets/door3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "5963",
    name: "Metal Door with full vision kit 4'x7'",
    category: "Door with Frame",
    Company: "Baron`",
    price: "3500",
    model: "door6.glb",
    title: "Metal Door with full vision kit 4'x7'",
    description:
      "Commerical steel grade doors and frame suitable for 4' x 8' with stylish FRV window. \n The finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/d1.png", "/assets/d2.png", "/assets/d3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "65175",
    name: "Metal Door with half vision kit 4' X 10'",
    category: "Door with Frame",
    Company: "Fleming",
    price: "1000",
    model: "door7.glb",
    title: "Metal Door with half vision kit 4' X 10'",
    description:
      "Commerical steel grade doors and frame suitable for 4' x 10'. \nThe finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/door2.png", "/assets/door1.png", "/assets/door3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "5963",
    name: " Only Frame",
    category: "Frame",
    Company: "Baron",
    price: "250",
    model: "door8.glb",
    title: "Only Frame",
    description: "Commerical steel grade frames as per your required size",
    images: ["/assets/s1.png", "/assets/s2.png", "/assets/s3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
  {
    id: "5973",
    name: " Double Door 6' x 8'",
    category: "Double Door",
    Company: "CECO",
    price: "2000",
    model: "door9.glb",
    title: "Double Door with Exit device 6' x 8'",
    description:
      "Commerical steel grade double doors and frame suitable for 6' x 8'.\nThe finish is extremely durable and is factory applied to ensure consistent & High quality results",
    images: ["/assets/d1.png", "/assets/d2.png", "/assets/d3.png"],
    colour: ["#A1662F", "#FFD700", "#727472", "#c6c8c9", "#C0C0C0"],
  },
];
